### ISSUE TITLE
how can i get access to admin dashboard?

### ISSUE THREAD

**Issue by Rohit939** [NishakMohomed/foodDelivery#1]
how can i get access to admin dashboard?
i tried alot but still couldn't get access to admin dashboard.
can you tell me how?

**Comment by NishakMohomed** [comment]
1. Create an user account normally
2. Then open mongoDB compass
3. There is a database called food-delivery
4. Go inside it and find the collection called users
5. Locate the data when the system stored while you created the user account
6. In there you can find a field called **role: "customer"**
7. Change that field data into admin like this **role: "admin"**
8. Don't forget to change the field called **promo: "true"**  to **promo: "false"**
9. That's it now you can login to the admin dashboard using that account
